name = 'honi-demo'
main = 'src/index.ts'
compatibility_date = '2024-09-23'
compatibility_flags = ['nodejs_compat']

[durable_objects]
bindings = [{ name = 'VELA_SUPPORT_DO', class_name = 'VelaSupportDO' }]

[[migrations]]
tag = 'v1'
new_classes = ['VelaSupportDO']
